<?php
return
        [
            'pages'=>
                [
                    'edit-comments.php',
                    'index.php',
                    'edit.php',
                    'tools.php',
                    'link-manager.php',
                    'edit.php?post_type=acf-field-group',
                    'plugins.php',
                    'themes.php',
                    'options-general.php',
                    'users.php'
                ],
            'administrator'=>1

        ];